version: "3.8"
services:
  cafe-reviews-database:
    container_name: cafe-reviews-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: hwnaginkyu42/cafe-reviews-database
    environment:
      - MARIADB_DATABASE=cafe-reviews
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    restart: always
